# Generated by Django 3.1.1 on 2020-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='site_username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
