# Generated by Django 3.1.1 on 2020-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0003_socialsite_site_suffix'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='site_logo_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
