# Generated by Django 3.1.1 on 2020-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0004_socialsite_site_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='site_channel_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
