# Generated by Django 3.1.1 on 2020-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0007_usermaster_user_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsite',
            name='site_base_url',
            field=models.CharField(max_length=200, verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='site_logo_url',
            field=models.CharField(default='', max_length=128, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='site_name',
            field=models.CharField(max_length=64, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='site_suffix',
            field=models.CharField(default='', max_length=64, verbose_name='Site Suffix'),
        ),
    ]
