# Generated by Django 3.1.1 on 2020-10-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0008_auto_20201009_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSiteDetails',
            new_name='UserSiteDetail',
        ),
    ]
