# Generated by Django 3.1.1 on 2020-10-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0009_auto_20201009_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialsite',
            name='site_channel_id',
        ),
        migrations.RemoveField(
            model_name='socialsite',
            name='site_username',
        ),
    ]
