# Generated by Django 3.1.1 on 2020-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0010_auto_20201009_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialsite',
            name='site_user_id_suffix',
            field=models.CharField(default='', max_length=64, verbose_name='Site USer ID Suffix'),
        ),
    ]
