# Generated by Django 2.1.1 on 2020-10-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysocial', '0011_socialsite_site_user_id_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsite',
            name='site_suffix',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Site Suffix'),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='site_user_id_suffix',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Site User ID Suffix'),
        ),
    ]
